### ISSUE TITLE
Config file naming and defaults

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-node#113]
In #110 we implemented a single config file which currently looks like this:
```Toml
[block_producer]
host_port = { host = "127.0.0.1", port = 8080 }
store_endpoint = "http://store:8000"

[rpc]
host_port = { host = "127.0.0.1", port = 8080 }
store_endpoint = "http://store:8000"
block_producer_endpoint = "http://block_producer:8001"

[store]
host_port = { host = "127.0.0.1", port = 8080 }
sqlite = "local.sqlite3"
genesis_filepath = "genesis.dat"
```

I think something more like this would be more intuitive:
```Toml
[block_producer]
endpoint = { host = "127.0.0.1", port = 8080 }
store_url = "http://store:8000"
     
[rpc]
endpoint = { host = "127.0.0.1", port = 8080 }
store_url = "http://store:8000"
block_producer_url = "http://block_producer:8001"

[store]
endpoint = { host = "127.0.0.1", port = 8080 }
database_filepath = "local.sqlite3"
genesis_filepath = "genesis.dat"
```

The main differences are:
- Instead of `host_port` we'd use `endpoint`. I think it is better than `host_port`, but I don't love `endpoint` either. Other options could be `server`, `binding`, or maybe something else.
- For upstream components we'd use `_url` rather than `_endpoint`. I think it differentiates these a bit better from the `endpoint`.
- Instead of `store.sqlite` we'd use `store.database_filepath`. Another option is to use just `store.database`. This would keep it a bit more flexible in case we use a different database (e.g., Postgres).

### Defaults
I'd prefer to use the defaults as sparsely as possible. I think making things explicit avoids confusion down the road.

So, maybe the only default that we need is the config file path when we start the server. I think the default there could be `miden.toml`. So, the following would be equivalent:

```
miden-node start
miden-node start --config miden.toml
```
Everything else would be provided via the config file (and maybe environment variables - though, this too could create confusion).
