### ISSUE TITLE
Need of a way to pre-fill DB with data at genesis or / and way to add data to the running DB `for testing`

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#127]
The Notes and Nullifiers tables are empty for now and the only way to be able to fill them up is through the `apply_block` method. 

https://github.com/0xPolygonMiden/miden-node/blob/59984a5d4969053c55edf148c978a30b0ada23e9/store/src/server/api.rs#L100-L130

For testing purposes we could have a way to pre-fill the DB with data at genesis or an easy way to add data while the DB runs.

Linked to: #97 and #126

**Comment by bobbinth** [comment]
I'd expand this issue a bit to make it more broadly about generating genesis files. Currently, all aspects of [generating genesis files](https://github.com/0xPolygonMiden/miden-node/blob/main/node/src/commands.rs#L61) are hard-coded in Rust. We should make it more flexible. I can think of the following improvements:

### Human-readable inputs
It would be great if we could supply inputs for `make-genesis` command via some human-readable file. This could be a JSON file of the following form:
```JSON
{
    "version": 0,
    "timestamp": 13456,
    "accounts": [
        {
            "type": "basic_wallet",
            "id": "0x123456",
            "seed": "0x1245",
            "auth": {
                "type": "RpoFalcon512",
                "seed": "0x12456"
            },
            "storage_mode": "local"
        },
        {
            "type": "fungible_faucet",
            "id": "0x123456",
            "seed": "0x12345",
            "token_symbol": "POL",
            "decimals": 9,
            "max_supply": 1000000000,
            "auth": {
                "type": "RpoFalcon512",
                "seed": "0x12456"
            },
            "storage_mode": "onchain"
        }
    ],
    "notes": [],
    "nullifiers": []
}
```
(we could also adapt other formats if it simplifies parsing)

The procedure would then parse the file, create the specified accounts, notes, and nullifiers (using procedures exposed in `miden-lib`), and then output the genesis file as it does now.

### Account exports
Right now, the genesis generation procedure exports just public-private key pairs for keys associated with with the accounts in the genesis file. Instead, I think we should output files which can then be easily imported into the client. Specifically, we can output one file per account - maybe with `.mac` extension.

We need to settle on the format for these files. At the very least account file should contain:
- Serialized `Account` struct.
- Optional `account_seed` that we get at account creation time.
- Account authentication info (i.e., schema + key info). Here, we might be fine with serializing schema + the seed from which private/public keys were derived.

But @igamigo can provide more input on whether anything else is needed for importing the account into the client.

**Comment by phklive** [comment]
@bobbinth, for now the `make_genesis` [function](https://github.com/0xPolygonMiden/miden-node/blob/3f64cf3413d358033f0b52acc1a8fd0cf5ed14d1/node/src/commands.rs#L61) creates 2 accounts by default: 
- Basic wallet 
- Basic fungible faucet

I have 4 questions with the addition of a genesis file (that would look like genesis.json or other file extension) :
- Should we make the genesis file TOML to keep the use of toml files as in miden.toml or more generally in rust? 
```toml
version = 0
timestamp = 13456
accounts = [
    {type = "basic_wallet", id = "0x123456", seed = "0x1245", storage_mode = "local", auth = {type = "RpoFalcon512", seed = "0x12456"}},
    {type = "fungible_faucet", id = "0x123456", seed = "0x12345", token_symbol = "POL", decimals = 9, max_supply = 1000000000, storage_mode = "onchain", auth = {type = "RpoFalcon512", seed = "0x12456"}}
]
notes = []
nullifiers = []
```
- Should we make the genesis file optional? 
- If the genesis file is optional, then should we keep the 2 accounts initialised at genesis or should we start from a blank state? 
- Why do we have the word `basic` in front of wallet and faucet? Does it mean that there is a `not_basic` faucet or wallet that have a different behaviour?
