### ISSUE TITLE
[Feature]: Refactor configuration file for improved inference

### ISSUE THREAD

**Issue by phklive** [0xPolygonMiden/miden-node#334]
### To whom is this feature for?

End user

### Why is is this feature needed?

As of now in the configuration file of the miden-node file we have some dependencies between components:

```toml
[block_producer]
endpoint = { host = "localhost", port = 48046 }
store_url = "http://localhost:28943"
verify_tx_proofs = true

[rpc]
endpoint = { host = "0.0.0.0", port = 57291 }
block_producer_url = "http://localhost:48046"
store_url = "http://localhost:28943"

[store]
endpoint = { host = "localhost", port = 28943 }
database_filepath = "miden-store.sqlite3"
genesis_filepath = "genesis.dat"
```

`block_producer` and `rpc` have the url of the `store` for example.

This could lead to easy mistakes when typing out the configuration or by having wrong url's. 

A way to solve this would be to let the components infer the url of the other components from the configuration file as follows: 

```toml
[block_producer]
endpoint = { host = "localhost", port = 48046 }
verify_tx_proofs = true

[rpc]
endpoint = { host = "0.0.0.0", port = 57291 }

[store]
endpoint = { host = "localhost", port = 28943 }
database_filepath = "miden-store.sqlite3"
genesis_filepath = "genesis.dat"
```

### How is this feature used?

This will enable to have slimmer and more readable configuration files, it will also reduce the amount of possible errors.

### Anything else?

Initial comment here: https://github.com/0xPolygonMiden/miden-node/pull/323#discussion_r1574248236
